[build]
  publish = "public"
  command = "composer install --ignore-platform-req=ext-gmp && npm run build"

[build.environment]
  PHP_VERSION = "8.1"

[build.lifecycle]
  postinstall = "sudo apt-get update && sudo apt-get install -y php8.1-gmp"
  
[submodule "vendor/symfony/polyfill-mbstring"]
    path = vendor/symfony/polyfill-mbstring
    url = https://github.com/symfony/polyfill-mbstring.git
